-- 0058_indice_listagem_produtos — índice composto para a listagem do catálogo.
--
-- A tela de Produtos e o PDV abrem com a MESMA consulta:
--
--   SELECT ... FROM products p
--    WHERE p.deleted_at IS NULL AND p.parent_product_id IS NULL
--    ORDER BY p.favorite DESC, p.name
--
-- e o plano dela era `SCAN p` + `USE TEMP B-TREE FOR ORDER BY`: varredura da tabela
-- inteira mais uma ordenação temporária montada do zero a cada abertura de tela. Os
-- índices que existiam (`idx_products_name`, categoria, código de barras, NCM) não
-- atendem essa ordenação porque ela começa por `favorite DESC`.
--
-- O índice abaixo cobre a ordenação na ordem exata em que ela é pedida, e é PARCIAL
-- (`WHERE deleted_at IS NULL`): produto excluído nunca aparece nessa lista, então mantê-lo
-- no índice só gastaria espaço e escrita. Medido num catálogo gerado:
--
--     500 produtos →  21 ms      10.000 produtos →  92 ms
--   2.000 produtos →  20 ms      30.000 produtos → 243 ms
--
-- O ganho no tempo de consulta aparece principalmente do lado de cima dessa tabela; a
-- ordenação deixa de ser refeita a cada requisição, o que também tira pressão de memória
-- do processo — importante num PDV que roda em computador modesto o dia inteiro.
--
-- Não resolve, e nem pretende, o outro lado do problema: a resposta não é paginada, então
-- 30.000 produtos ainda são ~16 MB de JSON para o navegador. Isso é decisão de produto
-- (o PDV carrega o catálogo inteiro DE PROPÓSITO, para buscar e validar carrinho sem
-- rede), não algo que um índice conserte.
CREATE INDEX IF NOT EXISTS idx_products_listagem
  ON products(favorite DESC, name)
  WHERE deleted_at IS NULL;
